"""Exact, versioned mapping for one observed legacy Luna writer shape.

This is deliberately a narrow format adapter, not a repair model: it moves
known fields, creates deterministic section identities, and rejects every
shape that would require editorial interpretation.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from pydantic import ValidationError

from app.contracts.script_qualification import QualifiedScriptOutput
from app.services.config_registry import content_hash


NORMALIZATION_VERSION = "script-writer-output-normalization.v1"
CONTRACT_SCHEMA_VERSION = "qualified-script-output.v1"
LEGACY_WRAPPED_SCHEMA = "LEGACY_WRAPPED_CANONICAL_SCRIPT_V1"


@dataclass(frozen=True, slots=True)
class NormalizedWriterOutput:
    classification: str
    payload: dict[str, Any]
    field_mapping: dict[str, Any]
    removed_wrapper_fields: dict[str, Any]
    reason_codes: list[str]


class WriterOutputNormalizationError(ValueError):
    """The legacy body is not exactly the supported non-semantic mapping."""


def validation_errors(value: Any) -> list[dict[str, Any]]:
    try:
        QualifiedScriptOutput.model_validate(value)
    except ValidationError as exc:
        return [dict(item) for item in exc.errors(include_url=False)]
    return []


def normalize_legacy_writer_output(value: Any) -> NormalizedWriterOutput:
    """Normalize only the persisted wrapper shape described in the incident.

    The canonical narration is the Gate-A canonical form: each original
    narration is retained verbatim in its section and the top-level string is
    the ordered, whitespace-trimmed narration concatenation. No factual text,
    evidence reference, heading, or claim is generated by this function.
    """

    if not isinstance(value, dict):
        raise WriterOutputNormalizationError("WRITER_NORMALIZATION_ROOT_NOT_OBJECT")
    language = value.get("language")
    wrapped = value.get("canonical_script")
    claims = value.get("claims")
    if (
        not isinstance(language, str)
        or not isinstance(wrapped, dict)
        or not isinstance(claims, list)
    ):
        raise WriterOutputNormalizationError("WRITER_NORMALIZATION_LEGACY_SHAPE_REQUIRED")
    source_sections = wrapped.get("sections")
    if not isinstance(source_sections, list) or not source_sections:
        raise WriterOutputNormalizationError("WRITER_NORMALIZATION_SECTIONS_REQUIRED")

    sections: list[dict[str, str]] = []
    preserved_section_metadata: list[dict[str, Any]] = []
    for position, source in enumerate(source_sections, start=1):
        if not isinstance(source, dict):
            raise WriterOutputNormalizationError("WRITER_NORMALIZATION_SECTION_NOT_OBJECT")
        heading = source.get("heading")
        narration = source.get("narration")
        claim_ids = source.get("claim_ids")
        section_role = source.get("section_role")
        if (
            not isinstance(heading, str)
            or not heading
            or not isinstance(narration, str)
            or not narration
            or not isinstance(claim_ids, list)
            or not all(isinstance(item, str) and item for item in claim_ids)
            or not isinstance(section_role, str)
            or not section_role
        ):
            raise WriterOutputNormalizationError(
                "WRITER_NORMALIZATION_SECTION_FIELDS_INVALID"
            )
        section_id = f"S{position:02d}"
        sections.append(
            {"section_id": section_id, "heading": heading, "narration": narration}
        )
        preserved_section_metadata.append(
            {
                "section_id": section_id,
                "source_index": position - 1,
                "section_role": section_role,
                "claim_ids": list(claim_ids),
            }
        )

    normalized_claims: list[dict[str, Any]] = []
    for source in claims:
        if not isinstance(source, dict):
            raise WriterOutputNormalizationError("WRITER_NORMALIZATION_CLAIM_NOT_OBJECT")
        claim_id = source.get("claim_id")
        claim_text = source.get("text")
        evidence_ids = source.get("factual_evidence_span_ids")
        if (
            not isinstance(claim_id, str)
            or not claim_id
            or not isinstance(claim_text, str)
            or not claim_text
            or not isinstance(evidence_ids, list)
            or not all(isinstance(item, str) and item for item in evidence_ids)
        ):
            raise WriterOutputNormalizationError(
                "WRITER_NORMALIZATION_CLAIM_FIELDS_INVALID"
            )
        normalized_claims.append(
            {
                "claim_id": claim_id,
                "claim_text": claim_text,
                "evidence_span_ids": list(evidence_ids),
            }
        )

    canonical_script = " ".join(section["narration"].strip() for section in sections).strip()
    if not canonical_script:
        raise WriterOutputNormalizationError("WRITER_NORMALIZATION_CANONICAL_SCRIPT_EMPTY")
    payload = {
        "language": language,
        "canonical_script": canonical_script,
        "sections": sections,
        "claims": normalized_claims,
    }
    try:
        typed = QualifiedScriptOutput.model_validate(payload)
    except ValidationError as exc:  # pragma: no cover - defensive contract coupling
        raise WriterOutputNormalizationError("WRITER_NORMALIZATION_CONTRACT_INVALID") from exc

    field_mapping = {
        "language": "language",
        "canonical_script": "canonical_script.sections[].narration -> ordered join with single spaces",
        "sections": {
            "source": "canonical_script.sections",
            "section_id": "generated deterministic ordinal S01, S02, ...",
            "heading": "heading",
            "narration": "narration",
        },
        "claims": {
            "claim_id": "claim_id",
            "claim_text": "text",
            "evidence_span_ids": "factual_evidence_span_ids",
        },
        "section_metadata_preserved": preserved_section_metadata,
    }
    removed_wrapper_fields = {
        "canonical_script.title": wrapped.get("title"),
        "canonical_script.sections[].section_role": [
            item["section_role"] for item in preserved_section_metadata
        ],
        "canonical_script.sections[].claim_ids": [
            item["claim_ids"] for item in preserved_section_metadata
        ],
    }
    return NormalizedWriterOutput(
        classification=LEGACY_WRAPPED_SCHEMA,
        payload=typed.model_dump(mode="json"),
        field_mapping=field_mapping,
        removed_wrapper_fields=removed_wrapper_fields,
        reason_codes=[
            "WRITER_OUTPUT_LEGACY_WRAPPER_NORMALIZED",
            "NO_SEMANTIC_REWRITE",
            f"NORMALIZED_PAYLOAD_HASH:{content_hash(typed.model_dump(mode='json'))}",
        ],
    )
