import { Badge } from "@/components/ui/badge";

const labels: Record<string, string> = {
  READY_FOR_HUMAN_REVIEW: "Chờ người duyệt",
  NEEDS_MORE_EVIDENCE: "Cần thêm bằng chứng",
  BLOCKED: "Đang bị chặn",
  APPROVED: "Đã duyệt",
  REJECTED: "Đã từ chối",
  STALE: "Dữ liệu cũ",
  UNKNOWN: "Chưa có dữ liệu",
  READY: "Đã sẵn sàng",
  PARTIAL: "Cần cấu hình",
  PASS: "Đã sẵn sàng",
  WARNING: "Cần cấu hình",
  PENDING: "Đang chờ",
  QUEUED: "Đang chờ",
  IN_PROGRESS: "Đang xử lý",
  COMPLETED: "Hoàn tất",
  DONE: "Hoàn tất",
  SUCCESS: "Thành công",
  ERROR: "Có lỗi",
  SKIPPED: "Đã bỏ qua kiểm tra",
  UNAVAILABLE: "Không khả dụng",
  NOT_AVAILABLE: "Không khả dụng",
  FRESH: "Dữ liệu mới",
  CURRENT: "Dữ liệu mới",
  NEEDS_AUTH: "Cần kết nối tài khoản",
  CONNECTED: "Đã kết nối",
  NOT_CONFIGURED: "Chưa cấu hình",
  FAILED: "Thất bại",
  VERIFIED: "Đã xác minh",
  CLEANED_LOCAL: "Đã dọn file local",
  CLEANED: "Đã dọn file local",
  ACTIVE: "Đang hoạt động",
  DRAFT: "Bản nháp",
  PAUSED: "Đang tạm dừng",
  DEACTIVATED: "Đã ngừng",
  ARCHIVED: "Đã lưu trữ",
  HEALTHY: "Ổn định",
  WATCHLIST: "Cần theo dõi",
  LOW_VIEW: "Views thấp",
  NO_VIEW: "Chưa có views",
  NEEDS_HUMAN_REVIEW: "Cần người duyệt",
  ACTION_REQUIRED: "Cần xử lý",
  CHECK_FRESHNESS: "Kiểm tra độ mới",
  WATCH: "Theo dõi",
  HIGH: "Ưu tiên cao",
  NORMAL: "Bình thường",
  LOW: "Thấp",
  CRITICAL: "Khẩn cấp",
  HARD_RULE: "Quy tắc bắt buộc",
  HUMAN_REQUIRED: "Cần người vận hành",
  SEE_EVIDENCE: "Xem bằng chứng",
  SEE_DIAGNOSTIC: "Xem chẩn đoán",
  SYSTEM_RECORDED: "Hệ thống đã ghi",
  CONFIGURED: "Đã cấu hình",
  READY_FOR_SMOKE: "Sẵn sàng kiểm tra",
  NEEDS_CREDENTIAL: "Thiếu thông tin kết nối",
  NEEDS_CONFIG: "Cần cấu hình",
  MISSING_REQUIRED_GAP: "Thiếu cấu hình bắt buộc",
  REQUIRED_GAP: "Thiếu renderer",
  SMOKE_PASS: "Kiểm tra thành công",
  SMOKE_FAILED: "Kiểm tra thất bại",
  SMOKE_SKIPPED: "Đã bỏ qua kiểm tra",
  GOOGLE_DRIVE_READY: "Google Drive sẵn sàng",
  NO_CLOUD_MEDIA: "Chưa có file Drive",
  NO_PROJECTS: "Chưa có dự án",
  PROJECTS_ACTIVE: "Có dự án",
  NO_HANDOFFS: "Chưa có gói publish",
  HANDOFFS_AVAILABLE: "Có gói publish",
  NO_LEARNING_REVIEW: "Chưa có bài học",
  LEARNING_REVIEW_READY: "Có bài học chờ duyệt",
  INSIDE: "Trong khung giờ",
  OUTSIDE: "Ngoài khung giờ",
  OK: "Ổn",
  REVIEW: "Cần review",
  AVAILABLE: "Có sẵn",
  CHANGED: "Đã thay đổi",
  STRONG: "Mạnh",
  WEAK: "Yếu",
  OBSERVING: "Đang quan sát",
  DISABLED: "Đang tắt",
  CONFIGURED_BY_CATALOG: "Cấu hình bằng catalog",
  NO_AUTO_PUBLISH: "Không tự publish",
  NO_RAW_LOG: "Không hiện log thô",
  DAILY_ALLOWED: "Được tạo daily",
  DAILY_BLOCKED: "Tạo hằng ngày đang bị chặn",
  READ_ONLY: "Chỉ đọc",
  READ_ONLY_OBSERVER: "Chỉ đọc",
  OWNER_ADMIN: "Chủ sở hữu/admin",
  CHANNEL_MANAGER: "Quản lý kênh",
  PRODUCER: "Nhà sản xuất",
  REVIEWER: "Người duyệt",
  PUBLISHER: "Người xác nhận publish",
  ANALYST: "Người phân tích",
  PROCUREMENT_OPERATOR: "Vận hành mua sắm",
  COMPLIANCE_REVIEWER: "Duyệt compliance",
  LEARNING_REVIEWER: "Duyệt bài học",
  SIZE_VERIFIED: "Đã xác minh dung lượng",
  SIZE_MISMATCH: "Dung lượng lệch",
  NOT_VERIFIED: "Chưa xác minh",
  UPLOADED: "Đã upload",
  UPLOAD_PENDING: "Chờ upload thủ công",
  READY_FOR_HUMAN_UPLOAD: "Cần upload thủ công",
  HUMAN_UPLOAD_IN_PROGRESS: "Đang upload thủ công",
  UPLOADED_WAITING_BACKFILL: "Chờ nhập video_id",
  BACKFILLED_WAITING_VERIFICATION: "Chờ xác minh YouTube",
  UPLOADED_VERIFIED: "Đã upload và xác minh",
  UPLOADED_UNVERIFIED: "Đã upload, chưa xác minh",
  PUBLISHED: "Đã publish",
  MANUAL_CONFIRMATION_PENDING: "Chờ xác nhận thủ công",
  VERIFIED_PUBLIC: "Đã xác minh public",
  VERIFIED_OWNER: "Đã xác minh owner",
  VERIFICATION_UNAVAILABLE: "Chưa kết nối YouTube",
  VERIFICATION_FAILED: "Xác minh thất bại",
  SYNCED: "Đã sync",
  PUBLIC: "Công khai",
  PRIVATE: "Riêng tư",
  UNLISTED: "Không công khai",
  SCHEDULED: "Đã lên lịch",
  YOUTUBE: "YouTube"
};

function toneFor(value: string) {
  const normalized = value.toUpperCase();
  if (["ACTIVE", "READY", "HEALTHY", "CONNECTED", "VERIFIED", "VERIFIED_PUBLIC", "VERIFIED_OWNER", "UPLOADED_VERIFIED", "SYNCED", "CURRENT", "FRESH", "APPROVED", "OK", "PASS", "SMOKE_PASS", "INSIDE", "READY_FOR_SMOKE", "COMPLETED", "DONE", "SUCCESS", "PUBLISHED", "SIZE_VERIFIED"].includes(normalized)) return "success";
  if (["PAUSED", "PARTIAL", "WARNING", "SKIPPED", "SMOKE_SKIPPED", "WATCHLIST", "STALE", "UNKNOWN", "NEEDS_AUTH", "NEEDS_CREDENTIAL", "NEEDS_CONFIG", "NEEDS_MORE_EVIDENCE", "REVIEW", "REVIEW_REQUIRED", "NEEDS_HUMAN_REVIEW", "PENDING", "QUEUED", "IN_PROGRESS", "UPLOAD_PENDING", "READY_FOR_HUMAN_UPLOAD", "HUMAN_UPLOAD_IN_PROGRESS", "UPLOADED_WAITING_BACKFILL", "BACKFILLED_WAITING_VERIFICATION", "UPLOADED_UNVERIFIED", "MANUAL_CONFIRMATION_PENDING", "NOT_VERIFIED", "VERIFICATION_UNAVAILABLE", "NOT_CONFIGURED"].includes(normalized)) return "warning";
  if (["BLOCKED", "BLOCK", "FAILED", "SMOKE_FAILED", "DEACTIVATED", "ARCHIVED", "MISSING_REQUIRED_GAP", "REQUIRED_GAP", "HIGH", "CRITICAL", "OUTSIDE", "ERROR", "SIZE_MISMATCH", "VERIFICATION_FAILED"].includes(normalized)) return "danger";
  if (["WEAK", "STRONG", "OBSERVING", "CONFIGURED"].includes(normalized)) return "info";
  return "neutral";
}

export function friendlyStatusLabel(value: string | number | null | undefined) {
  const raw = value === null || value === undefined || value === "" ? "UNKNOWN" : String(value);
  const mapped = labels[raw.toUpperCase()];
  if (mapped) return mapped;
  if (/^[A-Z0-9_:-]+$/.test(raw) || raw.includes("_")) return labels.UNKNOWN;
  return raw;
}

export function FriendlyStatusBadge({ value }: { value: string | number | null | undefined }) {
  const raw = value === null || value === undefined || value === "" ? "UNKNOWN" : String(value);
  return <Badge tone={toneFor(raw)}>{friendlyStatusLabel(raw)}</Badge>;
}
