from sqlalchemy import inspect, text
from sqlalchemy.engine import Engine


REQUIRED_TABLES = {
    "companies",
    "users",
    "roles",
    "user_roles",
    "audit_events",
    "domain_events",
    "llm_run_snapshots",
    "config_catalog_versions",
    "video_projects",
    "artifacts",
    "artifact_versions",
    "review_tasks",
    "review_findings",
    "revision_requests",
    "approval_decisions",
    "gate_definition_versions",
    "gate_runs",
    "platform_policy_catalogs",
    "platform_policy_versions",
    "policy_source_refs",
    "policy_change_records",
    "policy_revalidation_batches",
    "provider_registry_entries",
    "credential_references",
    "credential_health_snapshots",
    "quota_accounts",
    "quota_events",
    "cost_events",
    "budget_policies",
    "provider_health_snapshots",
    "component_health_snapshots",
    "system_health_snapshots",
    "retry_policies",
    "provider_attempts",
    "dead_letter_jobs",
    "ops_incidents",
    "manual_action_queue",
    "editorial_calendar_slots",
    "channel_daily_runs",
    "retrieval_plan_snapshots",
    "context_pack_snapshots",
    "channel_state_pack_snapshots",
    "search_demand_evidence",
    "search_intent_maps",
    "audience_target_packs",
    "idea_market_preflights",
    "daily_idea_decisions",
    "project_admission_decisions",
    "production_artifact_runs",
    "voice_timeline_snapshots",
    "caption_track_snapshots",
    "visual_plan_snapshots",
    "scene_manifest_snapshots",
    "asset_manifest_snapshots",
    "source_manifest_snapshots",
    "render_spec_snapshots",
    "media_render_jobs",
    "render_package_snapshots",
    "media_qc_reports",
    "accessibility_qc_reports",
    "pronunciation_dictionary_entries",
    "publish_handoff_packages",
    "manual_publish_confirmations",
    "uploaded_videos",
    "uploaded_video_publication_summaries",
    "analytics_sync_runs",
    "metric_definition_versions",
    "metric_availability_snapshots",
    "analytics_snapshots",
    "traffic_source_snapshots",
    "retention_curve_snapshots",
    "engagement_snapshots",
    "uploaded_video_metrics_summaries",
    "post_publish_observation_windows",
    "post_publish_health_runs",
    "diagnostic_taxonomy_versions",
    "no_view_diagnostic_runs",
    "packaging_diagnostic_runs",
    "retention_diagnostic_runs",
    "engagement_diagnostic_runs",
    "policy_rights_diagnostic_runs",
    "failure_trace_reports",
    "recovery_proposals",
}


def test_alembic_migration_applies_on_empty_postgres(engine: Engine) -> None:
    with engine.connect() as connection:
        revision = connection.execute(text("select version_num from alembic_version")).scalar_one()
    assert revision == "0010_m9_post_publish_diagnostics"


def test_core_tables_exist_after_migration(engine: Engine) -> None:
    tables = set(inspect(engine).get_table_names())
    assert REQUIRED_TABLES.issubset(tables)
