from sqlalchemy import inspect, text
from sqlalchemy.engine import Engine


REQUIRED_TABLES = {
    "companies",
    "users",
    "roles",
    "user_roles",
    "audit_events",
    "domain_events",
    "llm_run_snapshots",
    "config_catalog_versions",
    "video_projects",
    "artifacts",
    "artifact_versions",
    "review_tasks",
    "review_findings",
    "revision_requests",
    "approval_decisions",
    "gate_definition_versions",
    "gate_runs",
    "platform_policy_catalogs",
    "platform_policy_versions",
    "policy_source_refs",
    "policy_change_records",
    "policy_revalidation_batches",
    "provider_registry_entries",
    "credential_references",
    "credential_health_snapshots",
    "quota_accounts",
    "quota_events",
    "cost_events",
    "budget_policies",
    "provider_health_snapshots",
    "component_health_snapshots",
    "system_health_snapshots",
    "retry_policies",
    "provider_attempts",
    "dead_letter_jobs",
    "ops_incidents",
    "manual_action_queue",
    "editorial_calendar_slots",
    "channel_daily_runs",
    "retrieval_plan_snapshots",
    "context_pack_snapshots",
    "channel_state_pack_snapshots",
    "search_demand_evidence",
    "search_intent_maps",
    "audience_target_packs",
    "idea_market_preflights",
    "daily_idea_decisions",
    "project_admission_decisions",
    "production_artifact_runs",
    "voice_timeline_snapshots",
    "caption_track_snapshots",
    "visual_plan_snapshots",
    "scene_manifest_snapshots",
    "asset_manifest_snapshots",
    "source_manifest_snapshots",
    "render_spec_snapshots",
    "media_render_jobs",
    "render_package_snapshots",
    "media_qc_reports",
    "accessibility_qc_reports",
    "pronunciation_dictionary_entries",
    "publish_handoff_packages",
    "manual_publish_confirmations",
    "uploaded_videos",
    "uploaded_video_publication_summaries",
    "analytics_sync_runs",
    "metric_definition_versions",
    "metric_availability_snapshots",
    "analytics_snapshots",
    "traffic_source_snapshots",
    "retention_curve_snapshots",
    "engagement_snapshots",
    "uploaded_video_metrics_summaries",
    "post_publish_observation_windows",
    "post_publish_health_runs",
    "diagnostic_taxonomy_versions",
    "no_view_diagnostic_runs",
    "packaging_diagnostic_runs",
    "retention_diagnostic_runs",
    "engagement_diagnostic_runs",
    "policy_rights_diagnostic_runs",
    "failure_trace_reports",
    "recovery_proposals",
    "learning_candidate_generation_runs",
    "learning_candidates",
    "learning_evidence_bundles",
    "learning_promotion_eligibility_runs",
    "learning_review_queue_items",
    "playbook_candidate_drafts",
    "llm_router_profiles",
    "llm_router_lanes",
    "llm_model_profiles",
    "llm_route_attempts",
    "content_derivative_graph_edges",
    "short_candidates",
    "short_candidate_scores",
    "short_render_plans",
    "promote_short_to_long_candidates",
    "reusable_artifacts",
    "asset_reuse_index_entries",
    "derivative_originality_checks",
    "originality_budgets",
    "derivative_release_plans",
    "cross_platform_funnel_packages",
    "upload_cards",
    "human_upload_tasks",
    "usage_savings_ledger_entries",
    "media_provider_role_profiles",
    "provider_capability_matrix_entries",
    "media_render_routing_decisions",
    "media_provider_budget_policies",
    "media_provider_budget_snapshots",
    "long_form_render_packages",
    "short_render_packages",
    "ai_hero_assets",
    "creatomate_render_assets",
    "thumbnail_variants",
    "final_media_refs",
    "license_evidence_records",
    "youtube_monitoring_credentials",
    "youtube_oauth_sessions",
    "youtube_public_sync_runs",
    "youtube_owner_analytics_sync_runs",
    "uploaded_video_youtube_public_monitor_snapshots",
    "uploaded_video_youtube_owner_analytics_snapshots",
    "cloud_media_refs",
    "media_offload_jobs",
    "local_media_retention_policies",
    "google_drive_media_credentials",
    "google_drive_oauth_sessions",
    "channel_lifecycle_decisions",
    "learning_review_decisions",
    "approved_playbook_entries",
    "operator_users",
    "operator_auth_sessions",
    "localized_subtitle_packages",
    "localized_metadata_packages",
    "channel_publish_timing_policies",
    "publish_timing_suggestions",
}


def test_alembic_migration_applies_on_empty_postgres(engine: Engine) -> None:
    with engine.connect() as connection:
        revision = connection.execute(text("select version_num from alembic_version")).scalar_one()
    assert revision == "0017_m11_1_localization"


def test_core_tables_exist_after_migration(engine: Engine) -> None:
    tables = set(inspect(engine).get_table_names())
    assert REQUIRED_TABLES.issubset(tables)
