# ruff: noqa: F401, F811

import uuid
from typing import Any

from fastapi import FastAPI, HTTPException, Request, Response, status
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import RedirectResponse
from pydantic import BaseModel, ConfigDict

from app.contracts import (
    ApprovalDecisionCreate,
    ApprovalDecisionRead,
    AnalyticsSnapshotRead,
    AnalyticsSyncRunCreate,
    AnalyticsSyncRunExecuteRequest,
    AnalyticsSyncRunRead,
    ArtifactCreate,
    ArtifactRead,
    ArtifactVersionCreate,
    ArtifactVersionRead,
    BudgetGateCheckRequest,
    BudgetGateDecisionRead,
    BudgetPolicyCreate,
    BudgetPolicyRead,
    ChannelMembershipCreate,
    ChannelMembershipRead,
    ChannelProfileApprovalRequest,
    ChannelProfileCompileRequest,
    ChannelProfileCompileResult,
    ChannelProfileDraftUpdate,
    ChannelProfileRejectionRequest,
    ChannelProfileVersionCreate,
    ChannelProfileVersionRead,
    ChannelWorkspaceCreate,
    ChannelWorkspaceRead,
    CategoryCreativeDigestCreate,
    CategoryCreativeDigestRead,
    CharacterBindingCreate,
    CharacterBindingRead,
    CharacterImageBranchCreate,
    CharacterImageBranchRead,
    CharacterProfileCreate,
    CharacterProfileRead,
    CharacterReferenceAssetCreate,
    CharacterReferenceAssetPackCreate,
    CharacterReferenceAssetPackRead,
    CharacterReferenceAssetRead,
    CharacterVersionCreate,
    CharacterVersionRead,
    ContentCategoryCreate,
    ContentCategoryRead,
    VoiceProfileCreate,
    VoiceProfileRead,
    ComponentHealthSnapshotCreate,
    ComponentHealthSnapshotRead,
    CostEventCreate,
    CostEventRead,
    CredentialHealthSnapshotCreate,
    CredentialHealthSnapshotRead,
    CredentialReferenceCreate,
    CredentialReferenceRead,
    EditorialIdeaCandidateCreate,
    EditorialIdeaCandidateRead,
    EditorialIdeaCandidateTransition,
    EditorialResearchRunCreate,
    EditorialResearchRunRead,
    DeadLetterJobCreate,
    DeadLetterJobRead,
    EditorialCalendarSlotCreate,
    EditorialCalendarSlotRead,
    GateRunCreate,
    GateRunRead,
    IdeaMarketPreflightCreate,
    IdeaMarketPreflightRead,
    ManualActionCreate,
    ManualActionRead,
    ManualAnalyticsImportContract,
    ManualPublishConfirmationCreate,
    ManualPublishConfirmationRead,
    OpsIncidentCreate,
    OpsIncidentRead,
    PlatformPolicyCatalogCreate,
    PlatformPolicyCatalogRead,
    PlatformPolicyVersionCreate,
    PlatformPolicyVersionRead,
    PolicyChangeRecordCreate,
    PolicyChangeRecordRead,
    PolicyChangeStateRequest,
    PolicyRevalidationBatchCreate,
    PolicyRevalidationBatchRead,
    PolicySourceRefCreate,
    PolicySourceRefRead,
    ProviderAttemptRead,
    ProviderHealthCheckRequest,
    ProviderHealthSnapshotRead,
    ProviderRegistryEntryCreate,
    ProviderRegistryEntryRead,
    ProjectAdmissionDecisionRead,
    FailureTraceReportRead,
    LearningCandidateGenerationRunCreate,
    LearningCandidateGenerationRunExecuteRequest,
    LearningCandidateGenerationRunRead,
    LearningCandidateRead,
    LearningEvidenceBundleRead,
    LearningReviewQueueItemRead,
    AIHeroAssetPlanRequest,
    AIHeroAssetRead,
    AIHeroGenerationExecuteRequest,
    AIHeroGenerationJobRead,
    LicenseEvidenceGateCheckRequest,
    LicenseEvidenceGateRead,
    LongFormRenderPackageCreate,
    LongFormRenderPackageRead,
    MediaProviderBudgetCheckRequest,
    MediaProviderBudgetGateRead,
    MediaProviderBudgetPolicyRead,
    MediaProviderBudgetSnapshotRead,
    MediaProviderRoleProfileRead,
    MediaQCGateCheckRequest,
    MediaQCGateRead,
    MediaRenderRoutingDecisionRead,
    MediaRenderRoutingDecisionRequest,
    ProviderCapabilityGateCheckRequest,
    ProviderCapabilityGateRead,
    ProviderCapabilityMatrixEntryRead,
    ReusedContentRiskGateCheckRequest,
    ReusedContentRiskGateRead,
    ThumbnailVariantPlanRequest,
    ThumbnailVariantRead,
    LLMModelProfileRead,
    LLMRouteRequest,
    LLMRouteResponse,
    LLMRouterLaneRead,
    LLMRouterProfileRead,
    LLMRouterSmokeTestRead,
    LLMRouterSmokeTestRequest,
    ProductionArtifactRunCreate,
    ProductionArtifactRunRead,
    PostPublishHealthRunCreate,
    PostPublishHealthRunRead,
    PublishHandoffCreate,
    PublishHandoffRead,
    QCRunRequest,
    QuotaAccountCreate,
    QuotaAccountRead,
    QuotaEventRead,
    QuotaEventRequest,
    RetentionCurveSnapshotRead,
    RetrievalPlanSnapshotCreate,
    RetrievalPlanSnapshotRead,
    ReviewFindingCreate,
    ReviewFindingRead,
    ReviewTaskCreate,
    ReviewTaskRead,
    RevisionRequestCreate,
    RevisionRequestRead,
    RevisionResolveRequest,
    RetryPolicyCreate,
    RetryPolicyRead,
    SearchDemandEvidenceCreate,
    SearchDemandEvidenceRead,
    SystemHealthSnapshotRead,
    TrafficSourceSnapshotRead,
    UploadedVideoPublicationSummaryRead,
    UploadedVideoMetricsSummaryRead,
    UploadedVideoRead,
    UploadedVideoYouTubeFollowSummaryRead,
    CloudMediaReadPayload,
    GoogleDriveConnectionStatusRead,
    GoogleDriveOAuthSessionRead,
    LocalCleanupRunRequest,
    LocalCleanupRunResult,
    LocalMediaRetentionPolicyRead,
    MediaOffloadExecuteRequest,
    MediaOffloadJobCreate,
    MediaOffloadJobRead,
    VideoProjectCreate,
    VideoProjectRead,
    YouTubeConnectionStatusRead,
    YouTubeOAuthSessionRead,
    YouTubeOwnerAnalyticsSnapshotRead,
    YouTubeOwnerAnalyticsSyncRequest,
    YouTubeOwnerAnalyticsSyncRunRead,
    YouTubePublicMonitorSnapshotRead,
    YouTubePublicSyncRunRead,
    RecoveryProposalRead,
    PlaybookCandidateDraftRead,
    ChannelStatePackSnapshotCreate,
    ChannelStatePackSnapshotRead,
    ContextPackSnapshotCreate,
    ContextPackSnapshotRead,
    AuthLoginRequest,
    AuthSessionRead,
    ChannelLocalizationConfig,
    ChannelLocalizationConfigUpdate,
    ChannelPublishTimingPolicyRead,
    LocalizationReadinessGateRead,
    LocalizedMetadataPackageCreate,
    LocalizedMetadataPackageRead,
    LocalizedSubtitlePackageCreate,
    LocalizedSubtitlePackageRead,
    PublishTimingSuggestionRead,
    VideoProjectLocalizationRead,
    IntegrationReadinessRead,
    ProviderReadinessSnapshotRead,
    ProviderReadinessSnapshotM2Read,
    ProviderSmokeRequest,
    PromptEvaluationRunRead,
    PromptOutputValidationRequest,
    PromptOutputValidationResult,
    PromptRegistrySyncSummary,
    PromptRenderRequest,
    PromptRenderResult,
    PackagingHandoffSnapshotRead,
    ReadinessRunRequest,
    RealSmokeRunRead,
    FirstScriptedVideoPackageAgentRunsRead,
    FirstScriptedVideoPackageRead,
    FirstScriptedVideoPackageRequest,
    FirstScriptedVideoPackageReviewRead,
    M122SPreflightRead,
    VideoGenerationBoundaryRead,
    BackfillUploadedVideoRequest,
    BackfillUploadedVideoResult,
    HumanUploadTaskLedgerRead,
    HumanUploadTaskListRead,
    PublishLedgerRead,
    UploadedVideoLedgerRead,
    UploadedVideoListRead,
    UploadedVideoVerificationResult,
    ChannelMemoryItemRead,
    MemoryApprovalDecisionRead,
    MemoryApprovalRequest,
    MemoryFacetRead,
    MemoryFromApprovedPlaybookCreate,
    MemoryReviewQueueItemRead,
    ClosedLearningLoopStatusRead,
    LearningToMemoryPromotionRequest,
    LearningToMemoryPromotionRunRead,
    MemoryInfluenceManifestRead,
    QualityDeltaAttributionRead,
    QualityDeltaAttributionRunRequest,
    CostEstimateCreateRequest,
    CostEstimateSnapshotRead,
    HumanPaidRenderApprovalCreateRequest,
    HumanPaidRenderApprovalDecisionRequest,
    HumanPaidRenderApprovalRead,
    PaidAttemptLimitRecordRead,
    PaidProviderCallLedgerRead,
    ProviderBoundaryDecisionRead,
    ProviderBoundaryPreflightRequest,
    ProviderIdempotencyKeyCreateRequest,
    ProviderIdempotencyKeyRead,
    ProviderJobCreateRequest,
    ProviderJobSnapshotRead,
    ProxyPreviewArtifactFlagCreateRequest,
    ProxyPreviewArtifactFlagRead,
    RenderRevisionCreateRequest,
    RenderRevisionRead,
    ChannelRuntimeTraceRead,
    DiagnosticOpsQueueRead,
    LearningOpsQueueRead,
    MemoryInfluenceOpsRead,
    MemoryOpsQueueRead,
    OperatorNextActionRead,
    PackageOpsSummaryRead,
    PackagingApprovedPatchApplyAndRecheckResultRead,
    PackagingGateRerunRecordRead,
    PackagingPatchApplyRunRead,
    PackagingPatchApprovalDecisionRead,
    PackagingPatchDecisionRequest,
    PackagingReviewQueueRead,
    ProviderCostOpsRead,
    QualityDeltaOpsRead,
    RecoveryOpsQueueRead,
    RetrievalManifestOpsRead,
    RuntimeDashboardRead,
    RuntimeLTSFreezeCheckRead,
    UploadedVideoOpsSummaryRead,
    ChannelContractDraftRead,
    ChannelContractPreviewRead,
    ChannelContractReviewRequest,
    ChannelInitCompileRequest,
    ChannelInitCompileResult,
    ChannelInitDraftCreate,
    ChannelInitDraftRead,
    ChannelInitResearchRequest,
)
from app.contracts.policy_snapshot import CompiledChannelPolicySnapshot as SnapshotRead
from app.contracts.m11 import (
    ChannelLifecycleDecisionCreate,
    ChannelLifecycleDecisionRead,
    ChannelLifecycleRead,
    ChannelWorkspaceDashboardRead,
    CommandCenterRead,
    DashboardQueuesRead,
    LearningReviewDecisionCreate,
    LearningReviewDecisionRead,
    ProviderOpsDashboardRead,
    UploadedVideoDashboardRead,
    UploadedVideoListItem,
)
from app.core.config import get_settings
from app.core.db import check_database
from app.core.errors import (
    ConflictError,
    ForbiddenError,
    NotFoundError,
    ValidationFailureError,
)
from app.core.logging import configure_logging
from app.db.session import session_scope
from app.services import (
    AccessibilityQCService,
    AnalyticsSyncService,
    ChannelProfileCompiler,
    ChannelProfileService,
    ChannelWorkspaceService,
    CompanyService,
    PolicySnapshotService,
    ApprovalService,
    ArtifactService,
    ReviewService,
    VideoProjectService,
    GateDefinitionService,
    GateRunnerService,
    BudgetGateService,
    ChannelStatePackService,
    EditorialResearchService,
    ComponentHealthService,
    CostService,
    CredentialReferenceService,
    DeadLetterService,
    EditorialCalendarService,
    ManualActionService,
    ManualPublishConfirmationService,
    OpsIncidentService,
    PolicyCatalogService,
    PolicyChangeService,
    PolicyRevalidationService,
    IdeaMarketPreflightService,
    LocalFixtureRendererService,
    LearningCandidateGenerationService,
    LearningReadService,
    LearningReviewQueueService,
    AIHeroAssetPlanningService,
    AIHeroGenerationService,
    LicenseEvidenceGateService,
    LongFormRenderPackageService,
    MediaProviderBudgetService,
    MediaProviderRoleService,
    MediaQCGateService,
    MediaRenderJobRouterService,
    ProviderCapabilityGateService,
    ProviderCapabilityMatrixService,
    ReusedContentRiskGateService,
    ThumbnailVariantPlanningService,
    LLMRouterConfigLoader,
    LLMRouterService,
    MediaQCService,
    ProjectAdmissionService,
    ProviderHealthService,
    ProviderRegistryService,
    ProductionArtifactRunService,
    PostPublishHealthMonitorService,
    PublishHandoffService,
    QuotaService,
    R3D1AdminService,
    ResourceResolverService,
    RetryOpsService,
    SearchDemandEvidenceService,
    SystemHealthService,
    WorkflowReadinessService,
    UploadedVideoYouTubeFollowReadService,
    GoogleDriveCredentialHealthService,
    GoogleDriveOAuthSessionService,
    LocalMediaCleanupService,
    LocalMediaRetentionPolicyService,
    MediaCloudReadService,
    MediaOffloadJobService,
    YouTubeCredentialHealthService,
    YouTubeOAuthSessionService,
    YouTubeOwnerAnalyticsSyncService,
    YouTubePublicStatsSyncService,
    AuthService,
    LocalizationConfigService,
    LocalizationReadinessGateService,
    LocalizedMetadataPackageService,
    LocalizedSubtitlePackageService,
    PublishTimingPolicyService,
    PublishTimingSuggestionService,
    ProviderReadinessService,
    ProviderReadinessM2Service,
    PromptRegistryService,
    RealSmokeOrchestratorService,
    FirstScriptedVideoPackageService,
    PackagingHandoffReadService,
    PublishHandoffLedgerService,
    ControlledMemoryService,
    ClosedLearningLoopService,
    ChannelContractCompiler,
    ChannelContractReviewService,
    ChannelInitDraftService,
    ChannelSetupResearchAgentService,
    LearningToMemoryPromotionService,
    MemoryInfluenceManifestService,
    QualityDeltaAttributionService,
    CostEstimateService,
    HumanPaidRenderApprovalService,
    ChannelRuntimeTraceService,
    DiagnosticOpsService,
    LearningOpsService,
    MemoryInfluenceOpsService,
    MemoryOpsReadModelService,
    OperatorNextActionService,
    PackageOpsSummaryService,
    PackagingApprovedPatchApplyAndRecheckService,
    PackagingGateRerunService,
    PackagingPatchApplyService,
    PackagingPatchApprovalService,
    PackagingReviewQueueService,
    PaidProviderBoundaryService,
    ProviderCostOpsService,
    ProviderIdempotencyService,
    ProviderJobService,
    ProxyPreviewGate,
    QualityDeltaOpsService,
    RenderRevisionService,
    RecoveryOpsService,
    RetrievalOpsTraceService,
    RuntimeDashboardService,
    RuntimeLTSFreezeVerifier,
    UploadedVideoOpsService,
    evaluate_contract,
    leaf_values,
)
from app.services.m11 import (
    M11ChannelLifecycleService,
    M11DashboardService,
    M11LearningReviewService,
    channel_lifecycle_decision_read,
    learning_review_decision_read,
)
from app.services.m11_1 import AUTH_COOKIE_NAME


class CompanyCreate(BaseModel):
    name: str
    slug: str
    description: str = ""
    status: str = "active"
    default_currency: str = "USD"

    model_config = ConfigDict(extra="forbid")


class CompanyRead(BaseModel):
    id: uuid.UUID
    name: str
    slug: str
    description: str
    status: str
    default_currency: str

    model_config = ConfigDict(extra="forbid")


class ChannelCreateRequest(ChannelWorkspaceCreate):
    company_id: uuid.UUID

    model_config = ConfigDict(extra="forbid")


class ChannelActivateRequest(BaseModel):
    snapshot_id: uuid.UUID | None = None

    model_config = ConfigDict(extra="forbid")


__all__ = [name for name in globals() if not name.startswith("__")]
