from enum import StrEnum


class CompanyStatus(StrEnum):
    ACTIVE = "ACTIVE"
    PAUSED = "PAUSED"
    ARCHIVED = "ARCHIVED"


class WorkspaceStatus(StrEnum):
    ACTIVE = "ACTIVE"
    PAUSED = "PAUSED"
    ARCHIVED = "ARCHIVED"


class Platform(StrEnum):
    YOUTUBE = "youtube"
    TIKTOK = "tiktok"
    FACEBOOK = "facebook"
    INSTAGRAM = "instagram"


class MonetizationStatus(StrEnum):
    NOT_STARTED = "NOT_STARTED"
    VALIDATING = "VALIDATING"
    YPP_PROGRESS = "YPP_PROGRESS"
    MONETIZED = "MONETIZED"
    DEMONETIZED = "DEMONETIZED"
    SUSPENDED = "SUSPENDED"


class MaturityStage(StrEnum):
    NEW_CHANNEL = "NEW_CHANNEL"
    EXPLORING_CHANNEL = "EXPLORING_CHANNEL"
    GROWING_CHANNEL = "GROWING_CHANNEL"
    SCALED_CHANNEL = "SCALED_CHANNEL"
    MATURE_BRAND_CHANNEL = "MATURE_BRAND_CHANNEL"


class WorkflowMode(StrEnum):
    MONETIZATION_VALIDATION_MODE = "MONETIZATION_VALIDATION_MODE"
    FAST_TRACK = "FAST_TRACK"
    NORMAL_REUSE_FIRST = "NORMAL_REUSE_FIRST"
    PREMIUM_HYBRID = "PREMIUM_HYBRID"
    FULL_AI_CINEMATIC = "FULL_AI_CINEMATIC"


class MemoryScope(StrEnum):
    WORKSPACE_ONLY = "workspace_only"
    COMPANY_GLOBAL = "company_global"
    PLATFORM_GLOBAL = "platform_global"


class MemoryFamily(StrEnum):
    BRAND_IDENTITY = "brand_identity_memory"
    AUDIENCE = "audience_memory"
    UPLOADED_VIDEO = "uploaded_video_memory"
    PERFORMANCE = "performance_memory"
    BASELINE = "baseline_memory"
    EDITORIAL_PLAYBOOK = "editorial_playbook_memory"
    DIAGNOSIS = "diagnosis_memory"
    PRODUCTION_FAILURE = "production_failure_memory"
    REUSABLE_ASSET = "reusable_asset_memory"
    COMPLIANCE = "compliance_memory"
    MONETIZATION = "monetization_memory"


class ReviewTaskType(StrEnum):
    PRE_SPEND = "PRE_SPEND"
    FINAL_VIDEO = "FINAL_VIDEO"
    SALVAGE = "SALVAGE"


class ReviewTaskStatus(StrEnum):
    OPEN = "OPEN"
    APPROVED = "APPROVED"
    CHANGES_REQUESTED = "CHANGES_REQUESTED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"


class ReviewActionType(StrEnum):
    PRE_APPROVE = "PRE_APPROVE"
    DOWNGRADE_MODE = "DOWNGRADE_MODE"
    APPROVE = "APPROVE"
    REQUEST_CHANGES = "REQUEST_CHANGES"
    REJECT = "REJECT"
    PUBLISH_ANYWAY = "PUBLISH_ANYWAY"
    CONVERT_TO_EVERGREEN = "CONVERT_TO_EVERGREEN"
    REPURPOSE_ASSET = "REPURPOSE_ASSET"
    ARCHIVE_FOR_REUSE = "ARCHIVE_FOR_REUSE"


class AuthorityDecisionType(StrEnum):
    APPROVE_TOPIC = "APPROVE_TOPIC"
    REQUEST_MORE_RESEARCH = "REQUEST_MORE_RESEARCH"
    REJECT_TOPIC = "REJECT_TOPIC"
    KILL_TOPIC = "KILL_TOPIC"
    APPROVE_SCRIPT = "APPROVE_SCRIPT"
    REQUEST_SCRIPT_REVISION = "REQUEST_SCRIPT_REVISION"
    REJECT_SCRIPT = "REJECT_SCRIPT"
    PASS_TO_HUMAN = "PASS_TO_HUMAN"
    REQUEST_MEDIA_FIX = "REQUEST_MEDIA_FIX"
    REQUEST_SCRIPT_FIX = "REQUEST_SCRIPT_FIX"
    KILL_RENDER = "KILL_RENDER"
    CONTINUE_CURRENT_PLAYBOOK = "CONTINUE_CURRENT_PLAYBOOK"
    MINOR_TUNING = "MINOR_TUNING"
    CORRECTIVE_ACTION = "CORRECTIVE_ACTION"
    PAUSE_SIMILAR_PRODUCTION = "PAUSE_SIMILAR_PRODUCTION"


class ProjectState(StrEnum):
    COMPANY_WAKEUP = "COMPANY_WAKEUP"
    WORKSPACES_LOADED = "WORKSPACES_LOADED"
    WORKSPACE_MATURITY_UPDATED = "WORKSPACE_MATURITY_UPDATED"
    WORKSPACE_DAILY_PLAN_CREATED = "WORKSPACE_DAILY_PLAN_CREATED"
    IDEA_FOUND = "IDEA_FOUND"
    RESEARCHED = "RESEARCHED"
    TOPIC_REVIEW = "TOPIC_REVIEW"
    TOPIC_APPROVED = "TOPIC_APPROVED"
    TOPIC_REJECTED = "TOPIC_REJECTED"
    COST_AND_URGENCY_CHECK = "COST_AND_URGENCY_CHECK"
    PRE_PRODUCTION_PACK_CREATED = "PRE_PRODUCTION_PACK_CREATED"
    WAITING_HUMAN_PRE_APPROVAL = "WAITING_HUMAN_PRE_APPROVAL"
    PRE_APPROVED = "PRE_APPROVED"
    PRE_APPROVAL_REJECTED = "PRE_APPROVAL_REJECTED"
    PRE_APPROVAL_EXPIRED = "PRE_APPROVAL_EXPIRED"
    SCRIPT_DRAFTED = "SCRIPT_DRAFTED"
    SCRIPT_CRITIQUED = "SCRIPT_CRITIQUED"
    SCRIPT_REVIEW = "SCRIPT_REVIEW"
    SCRIPT_APPROVED = "SCRIPT_APPROVED"
    SCRIPT_REVISION_REQUESTED = "SCRIPT_REVISION_REQUESTED"
    SCRIPT_REJECTED = "SCRIPT_REJECTED"
    STORYBOARD_CREATED = "STORYBOARD_CREATED"
    PROMPTS_CREATED = "PROMPTS_CREATED"
    ASSET_CONTEXT_CREATED = "ASSET_CONTEXT_CREATED"
    REUSABLE_ASSET_SEARCHED = "REUSABLE_ASSET_SEARCHED"
    ASSET_REUSED = "ASSET_REUSED"
    ASSET_GENERATED = "ASSET_GENERATED"
    MEDIA_GENERATED = "MEDIA_GENERATED"
    VOICE_GENERATED = "VOICE_GENERATED"
    SUBTITLE_CREATED = "SUBTITLE_CREATED"
    LOWFI_RENDERED = "LOWFI_RENDERED"
    LOWFI_QA_PASSED = "LOWFI_QA_PASSED"
    RENDER_TIMELINE_SAVED = "RENDER_TIMELINE_SAVED"
    CHUNKED_RENDERED = "CHUNKED_RENDERED"
    HIFI_RENDERED = "HIFI_RENDERED"
    MEDIA_QA = "MEDIA_QA"
    COMPLIANCE_CHECKED = "COMPLIANCE_CHECKED"
    AUTHORITY_FINAL_REVIEW = "AUTHORITY_FINAL_REVIEW"
    SEO_METADATA_CREATED = "SEO_METADATA_CREATED"
    REVIEW_TASK_CREATED = "REVIEW_TASK_CREATED"
    WAITING_HUMAN_REVIEW = "WAITING_HUMAN_REVIEW"
    REVIEW_SLA_WARNING = "REVIEW_SLA_WARNING"
    HUMAN_APPROVED = "HUMAN_APPROVED"
    HUMAN_REQUESTED_CHANGES = "HUMAN_REQUESTED_CHANGES"
    HUMAN_REJECTED = "HUMAN_REJECTED"
    PRE_PUBLISH_REVERIFY = "PRE_PUBLISH_REVERIFY"
    SALVAGE_REQUIRED = "SALVAGE_REQUIRED"
    SALVAGE_PLAN_CREATED = "SALVAGE_PLAN_CREATED"
    CONVERTING_TO_EVERGREEN = "CONVERTING_TO_EVERGREEN"
    REPURPOSING_ASSETS = "REPURPOSING_ASSETS"
    ARCHIVED_FOR_REUSE = "ARCHIVED_FOR_REUSE"
    PUBLISHED = "PUBLISHED"
    PUBLISH_DETECTED = "PUBLISH_DETECTED"
    ANALYTICS_2H_COLLECTED = "ANALYTICS_2H_COLLECTED"
    ANALYTICS_4H_COLLECTED = "ANALYTICS_4H_COLLECTED"
    ANALYTICS_24H_COLLECTED = "ANALYTICS_24H_COLLECTED"
    ANALYTICS_48H_COLLECTED = "ANALYTICS_48H_COLLECTED"
    ANALYTICS_7D_COLLECTED = "ANALYTICS_7D_COLLECTED"
    AUTHORITY_POST_REVIEW = "AUTHORITY_POST_REVIEW"
    PLAYBOOK_NO_CHANGE = "PLAYBOOK_NO_CHANGE"
    PLAYBOOK_MINOR_TUNING = "PLAYBOOK_MINOR_TUNING"
    PLAYBOOK_CORRECTIVE_ACTION = "PLAYBOOK_CORRECTIVE_ACTION"
    MEMORY_UPDATED = "MEMORY_UPDATED"
